In [8]:
import pandas as pd
from PycalcAct.dataset import FromLegendFileCSV


df1 = pd.read_csv("../data/calciumBound.csv", header=None)
df2 = pd.read_csv("../data/calciumFree.csv", header=None)

# file = FromLegendFileCSV("../data/legend.csv")
# df1 = df1[file.filter]
# df2 = df2[file.filter]

In [9]:
df1.shape, df2.shape

((64507, 120), (64507, 120))

In [10]:
df1["feature"] = "calciumBound"
df2["feature"] = "calciumFree"

df4 = pd.merge(df1, df2, how="outer")
df4

,0,1,2,3,4,5,6,7,8,9,...,111,112,113,114,115,116,117,118,119,feature
0,4.485388,59.341961,61.001725,59.632641,62.175765,63.495725,64.558963,61.019924,60.914378,58.657459,...,64.372145,62.678514,60.721397,64.362182,60.479996,70.796173,71.554470,57.830174,54.614750,calciumBound
1,4.738958,6.076087,5.690707,4.966859,2.998264,8.113186,6.853452,7.797966,10.783063,11.461740,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,calciumBound
2,5.497785,29.412895,30.988674,29.165361,29.373484,31.192707,31.655801,31.255696,34.814495,34.631539,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,calciumBound
3,5.630780,12.898516,7.155942,8.205392,23.283810,20.111929,14.861740,17.533598,28.937511,34.982659,...,31.255257,32.152159,28.961287,31.847549,33.475104,37.126459,36.099313,33.034006,34.738551,calciumBound
4,5.706580,4.520876,6.344773,4.721100,4.071171,5.407269,5.001927,5.229239,6.249603,6.324442,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,calciumBound
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,152.331140,148.926205,157.469273,154.478324,149.849503,157.452038,151.041895,176.173601,182.256290,calciumFree
129010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,400.639746,360.358904,372.502289,304.299475,279.623546,225.168451,334.699378,450.608212,258.781584,calciumFree
129011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,228.689484,223.707003,202.019641,196.451996,197.639755,190.401143,197.291237,184.164567,175.044314,calciumFree
129012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,329.704166,308.636229,302.422273,302.311741,294.343287,310.142557,319.540482,307.002853,284.223089,calciumFree
129013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,329.704166,308.636229,302.422273,302.311741,294.343287,310.142557,319.540482,307.002853,284.223089,calciumFree

In [11]:
df1.iloc[:, 1]

0        27.122993
1        37.997206
2        58.994067
3        40.409519
4        70.312356
           ...
64502          NaN
64503          NaN
64504          NaN
64505          NaN
64506          NaN
Name: 1, Length: 64507, dtype: float64

In [12]:
df1 = pd.read_csv("../data/calciumBound.csv", header=None)
df2 = pd.read_csv("../data/calciumFree.csv", header=None)


print("Common rows:", (df1 == df2).all(axis=1).sum())
(df1 == df2).all(axis=1)

Common rows: 0

0        False
1        False
2        False
3        False
4        False
         ...
64502    False
64503    False
64504    False
64505    False
64506    False
Length: 64507, dtype: bool

In [13]:
(df1 == df2).all(axis=1)

0        False
1        False
2        False
3        False
4        False
         ...
64502    False
64503    False
64504    False
64505    False
64506    False
Length: 64507, dtype: bool

In [14]:
df1.index[(df1 == df2).all(axis=1)]

Index([], dtype='int64')